# Generated by Django 3.0.7 on 2020-06-19 18:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/none/no_product.png', upload_to='media/')),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('type_user', models.CharField(default='client', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
    ]
